//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.17 at 05:35:25 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://code.academy.pl/countries/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.academy.code.countries;
